In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data_train.csv')

In [27]:
df.head(20)

,Unnamed: 0,hash,trajectory_id,time_entry,time_exit,vmax,vmin,vmean,x_entry,y_entry,x_exit,y_exit,time_entry_formatted,time_exit_formatted
0,0,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_0,07:04:31,07:08:32,NaN,NaN,NaN,3.751014e+06,-1.909398e+07,3.750326e+06,-1.913634e+07,07:04:31,07:08:32
1,1,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_1,07:20:34,07:25:42,NaN,NaN,NaN,3.743937e+06,-1.932247e+07,3.744975e+06,-1.931966e+07,07:20:34,07:25:42
2,2,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_2,07:53:32,08:03:25,NaN,NaN,NaN,3.744868e+06,-1.929356e+07,3.744816e+06,-1.929284e+07,07:53:32,08:03:25
3,3,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_3,08:17:50,08:37:23,NaN,NaN,NaN,3.744880e+06,-1.929229e+07,3.744809e+06,-1.929049e+07,08:17:50,08:37:23
4,4,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_4,14:38:09,14:38:09,NaN,NaN,NaN,3.744909e+06,-1.928558e+07,3.744909e+06,-1.928558e+07,14:38:09,14:38:09
5,5,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_5,15:02:31,15:18:33,NaN,NaN,NaN,3.744945e+06,-1.928183e+07,3.744785e+06,-1.928148e+07,15:02:31,15:18:33
6,6,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_0,14:29:23,14:29:23,0.000000,0.000000,0.000000,3.749450e+06,-1.926506e+07,3.749450e+06,-1.926506e+07,14:29:23,14:29:23
7,7,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_1,14:39:49,14:39:49,0.000000,0.000000,0.000000,3.749090e+06,-1.926726e+07,3.749090e+06,-1.926726e+07,14:39:49,14:39:49
8,8,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_2,14:50:14,14:50:14,0.507809,0.507809,0.507809,3.749042e+06,-1.926632e+07,3.749042e+06,-1.926632e+07,14:50:14,14:50:14
9,9,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_3,15:00:32,15:29:48,1.149404,1.149404,1.149404,3.749088e+06,-1.926605e+07,3.749610e+06,-1.926594e+07,15:00:32,15:29:48
10,10,0001f97b99a80f18f62e2d44e54ef33d_3,traj_0001f97b99a80f18f62e2d44e54ef33d_3_0,11:37:06,11:52:08,32.196255,32.196255,32.196255,3.771461e+06,-1.910413e+07,3.757004e+06,-1.929698e+07,11:37:06,11:52:08
11,11,0001f97b99a80f18f62e2d44e54ef33d_3,traj_0001f97b99a80f18f62e2d44e54ef33d_3_1,14:34:35,15:19:51,30.167742,30.167742,30.167742,3.758738e+06,-1.937594e+07,3.769687e+06,-1.914258e+07,14:34:35,15:19:51
12,12,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_1,09:56:08,09:56:08,NaN,NaN,NaN,3.765544e+06,-1.917227e+07,3.765544e+06,-1.917227e+07,09:56:08,09:56:08
13,13,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_2,10:17:00,10:17:00,NaN,NaN,NaN,3.766338e+06,-1.917967e+07,3.766338e+06,-1.917967e+07,10:17:00,10:17:00
14,14,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_4,12:38:33,12:38:33,NaN,NaN,NaN,3.767863e+06,-1.917851e+07,3.767863e+06,-1.917851e+07,12:38:33,12:38:33
15,15,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_5,13:57:02,13:59:00,NaN,NaN,NaN,3.767864e+06,-1.917860e+07,3.767865e+06,-1.917859e+07,13:57:02,13:59:00
16,16,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_6,14:09:16,14:09:16,NaN,NaN,NaN,3.763879e+06,-1.921491e+07,3.763879e+06,-1.921491e+07,14:09:16,14:09:16
17,17,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_7,14:19:32,14:19:32,NaN,NaN,NaN,3.759740e+06,-1.921491e+07,3.759740e+06,-1.921491e+07,14:19:32,14:19:32
18,18,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_8,14:29:36,14:29:36,NaN,NaN,NaN,3.756596e+06,-1.921483e+07,3.756596e+06,-1.921483e+07,14:29:36,14:29:36
19,19,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_9,14:39:37,14:59:01,NaN,NaN,NaN,3.760046e+06,-1.923746e+07,3.768391e+06,-1.920211e+07,14:39:37,14:59:01

In [16]:
df_convert = pd.to_datetime(df['time_exit'], format='%H:%M:%S').dt.time

In [17]:
df['time_exit_formatted'] = df_convert

In [21]:
df['time_entry_formatted'].describe()

count       814262
unique       56765
top       15:03:00
freq           103
Name: time_entry_formatted, dtype: object

In [28]:
df[df['hash'] == '0000cf177130469eeac79f67b6bcf3df_9']

,Unnamed: 0,hash,trajectory_id,time_entry,time_exit,vmax,vmin,vmean,x_entry,y_entry,x_exit,y_exit,time_entry_formatted,time_exit_formatted
6,6,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_0,14:29:23,14:29:23,0.000000,0.000000,0.000000,3.749450e+06,-1.926506e+07,3.749450e+06,-1.926506e+07,14:29:23,14:29:23
7,7,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_1,14:39:49,14:39:49,0.000000,0.000000,0.000000,3.749090e+06,-1.926726e+07,3.749090e+06,-1.926726e+07,14:39:49,14:39:49
8,8,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_2,14:50:14,14:50:14,0.507809,0.507809,0.507809,3.749042e+06,-1.926632e+07,3.749042e+06,-1.926632e+07,14:50:14,14:50:14
9,9,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_3,15:00:32,15:29:48,1.149404,1.149404,1.149404,3.749088e+06,-1.926605e+07,3.749610e+06,-1.926594e+07,15:00:32,15:29:48